name: Test build backend

on:
  pull_request:
    paths:
      - "backend/**"

  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - run: npm run build
        working-directory: backend
