import { Router } from "express";

import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import quickAnswerRoutes from "./quickAnswerRoutes";
import apiRoutes from "./apiRoutes";
import healthRoutes from "./healthRoutes";
import reportTalkRoutes from "./reportTalkRoutes";
import ticketsReportRoutes from "./ticketsReportRoutes";
import ticketsExportReportRoutes from "./ticketsExportReportRoutes";
import ticketsExportReportTalkRoutes from "./ticketsExportReportTalkRoutes";
import fileRoutes from "./fileRoutes";
import registerRoutes from "./registersRoutes";
import templateRoutes from "./templateRoutes";
import whatsConfigRoutes from "./whatsConfigRoutes";
import companyRoutes from "./companyRoutes";
import menuRoutes from "./menuRoutes";
import templateDataRoutes from "./templateDataRoutes";
import productRoutes from "./productRoutes";
import pricingRoutes from "./pricingRoutes";
import integratedImportRoutes from "./integratedImportRoutes";
import historicRoutes from "./historicRoutes";
import billingsRoutes from "./billingsRoutes";
import categoryRoutes from "./categoryRoutes";
import flowsRoutes from "./flowsRoutes";
import connectionFilesRoutes from "./connectionFilesRoutes";
import exposedImportRoutes from "./exposedImportRoutes";
import nodeRegistersRoutes from "./nodeRegistersRoutes";

const routes = Router();

routes.use(userRoutes);
routes.use("/auth", authRoutes);
routes.use(settingRoutes);
routes.use(contactRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(queueRoutes);
routes.use(quickAnswerRoutes);
routes.use(healthRoutes);
routes.use("/api/messages", apiRoutes);
routes.use(reportTalkRoutes);
routes.use(ticketsReportRoutes);
routes.use(ticketsExportReportRoutes);
routes.use(ticketsExportReportTalkRoutes);
routes.use(fileRoutes);
routes.use(registerRoutes);
routes.use(templateRoutes);
routes.use(whatsConfigRoutes);
routes.use(companyRoutes);
routes.use(menuRoutes);
routes.use(templateDataRoutes);
routes.use(productRoutes);
routes.use(pricingRoutes);
routes.use(integratedImportRoutes);
routes.use(historicRoutes);
routes.use(billingsRoutes);
routes.use(categoryRoutes);
routes.use(flowsRoutes);
routes.use(connectionFilesRoutes);
routes.use(exposedImportRoutes);
routes.use(nodeRegistersRoutes);

export default routes;
