name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 387274513997.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: whatsapp-portal-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 3.17.162.231
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop whatsapp-api || true
            docker rm whatsapp-api || true
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            docker run -d --name whatsapp-api -p 80:80 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
