name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: main
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::387274513997:role/gihub-cicd
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 387274513997.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 387274513997.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: whatsapp-portal-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}} ./backend
          docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-18-218-140-72.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            docker stop whatsapp-api || true
            docker rm whatsapp-api || true
            docker pull ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
            docker run -d --name whatsapp-api -p 80:80 ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
