name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  build-and-deploy-api:
    env:
      ECR_REGISTRY: 387274513997.dkr.ecr.us-east-2.amazonaws.com
      ECR_REPOSITORY: whatsapp-portal-api
      IMAGE_TAG: ${{ github.sha }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_USER: ${{ secrets.DB_USER }}
    runs-on: self-hosted
    environment: homolog
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::387274513997:role/gihub-cicd
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 387274513997.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}} ./backend
          docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-19-137-63.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{secrets.KEY}}
          script: |
            docker stop whatsapp-api || true
            docker rm whatsapp-api || true
            docker pull ${{secrets.ECR_REGISTRY}}/${{secrets.ECR_REPOSITORY}}:${{github.sha}}
            docker run -d -e DB_HOST=${{secrets.DB_HOST}} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASS=${{ secrets.DB_PASS }} -e DB_NAME=${{ secrets.DB_NAME }}  --name whatsapp-api -p 8443:3000 ${{secrets.ECR_REGISTRY}}/${{secrets.ECR_REPOSITORY}}:${{github.sha}}
  build-and-deploy-frontend:
    env:
      ECR_REGISTRY: 387274513997.dkr.ecr.us-east-2.amazonaws.com
      ECR_REPOSITORY: whatsapp-portal-frontend
      IMAGE_TAG: ${{ github.sha }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_USER: ${{ secrets.DB_USER }}
      REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      REACT_APP_WORKER_URL: ${{secrets.REACT_APP_WORKER_URL}}
      REACT_APP_SQS_URL: ${{secrets.REACT_APP_SQS_URL}}

    runs-on: self-hosted
    environment: homolog
    needs: build-and-deploy-api
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::387274513997:role/gihub-cicd
          aws-region: us-east-1

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 387274513997.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        run: |
          docker build \
          --build-arg REACT_APP_BACKEND_URL=http://omni.brainitsolutions.com.br:8443 \
          --build-arg REACT_APP_WORKER_URL=$REACT_APP_WORKER_URL \
          --build-arg REACT_APP_SQS_URL="secrets.REACT_APP_SQS_URL \
          -t 387274513997.dkr.ecr.us-east-2.amazonaws.com/whatsapp-portal-frontend:${{env.IMAGE_TAG}} ./frontend 
          docker push 387274513997.dkr.ecr.us-east-2.amazonaws.com/whatsapp-portal-frontend:${{env.IMAGE_TAG}}

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-19-137-63.us-east-2.compute.amazonaws.com
          username: ubuntu
          key: ${{secrets.KEY}}
          script: |
            docker stop whatsapp-portal-frontend || true
            docker rm whatsapp-portal-frontend || true
            docker pull 387274513997.dkr.ecr.us-east-2.amazonaws.com/whatsapp-portal-frontend:${{github.sha}}
            docker run -d -e REACT_APP_BACKEND_URL=http://omni.brainitsolutions.com.br:8443 -e REACT_APP_WORKER_URL=http://omni.brainitsolutions.com.br:8444 -e REACT_APP_SQS_URL=http://omni.brainitsolutions.com.br:8445 --name whatsapp-portal-frontend -p 80:80 387274513997.dkr.ecr.us-east-2.amazonaws.com/whatsapp-portal-frontend:${{github.sha}}
